spring.application.name=thymeleaf

# JDBC 설정 > HikariCP > DBCP 구축
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=springboot
spring.datasource.password=java1234

# Mybatis 설정
# mybatis.config-location=classpath:config/mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.test.java.model